
--?? 1?? Script Base de Datos – Oracle 19c
CREATE TABLE CLIENTE_J (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    EDAD NUMBER,
    CIUDAD VARCHAR2(100),
    TIPO_CLIENTE VARCHAR2(50), -- Regular, Premium, VIP
    FECHA_REGISTRO DATE DEFAULT SYSDATE
);

COMMIT;

--? Datos de ejemplo
INSERT INTO CLIENTE_J (NOMBRE, EDAD, CIUDAD, TIPO_CLIENTE) 
VALUES ('Carlos', 25, 'Bogotá', 'Regular');

INSERT INTO CLIENTE_J (NOMBRE, EDAD, CIUDAD, TIPO_CLIENTE) 
VALUES ('Ana', 30, 'Medellín', 'Premium');

INSERT INTO CLIENTE_J (NOMBRE, EDAD, CIUDAD, TIPO_CLIENTE) 
VALUES ('Luis', 40, 'Cali', 'VIP');

COMMIT;